title: Exasol Secrets
description: Blog about hidden capabilities of analytical DBMS Exasol
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://wildraid.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Vitaly Markov"
image: /thumbnail-jumbo.png

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

talkyard_server_url: https://comments-for-wildraid-github-io.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

