title: Exasol Secrets
description: A little blog about efficiency and hidden features of analytical DBMS Exasol
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://exasecrets.com" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Vitaly Markov"

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_pages:
  - updates.md
  - about.md

google_analytics: UA-142190441-1

# gems:
#  - jekyll-seo-tag

talkyard_server_url: https://comments-for-wildraid-github-io.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
